name: Run Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary
      - name: Download ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
      - name: Start Xvfb (virtual display)
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
      - name: Run Robot Framework tests
        run: |
          robot saucedemo/tests/ || true
          robot todo_manager/tests/ || true
          robot testfire_bank/tests/ || true
      - name: Upload Robot Framework results
        uses: actions/upload-artifact@4
        with:
          name: robot-results
          path: |
            ./output.xml
            ./log.html
            ./report.html
